In [1]:
1+2

3

In [2]:
(1+2*3-4)/5

0.6

In [3]:
2**8

256

In [4]:
x=1
y=1/3
x+y

1.3333333333333333

In [5]:
Data_1=1/5
Data_2=3/5
Data_1+Data_2

0.8

In [6]:
type(100)

int

In [7]:
type(100.)

float

In [8]:
x=100
type(x)

int

In [9]:
x=100.1
type(x)

float

In [10]:
x='learning'
type(x)

str

In [11]:
x="learing"
type(x)

str

In [1]:
x=1/3
print(x)
y=2/3
print(y)

0.3333333333333333
0.6666666666666666


In [2]:
x

0.3333333333333333

In [3]:
print('x= ' + str(x))

x= 0.3333333333333333


In [4]:
print("x= " + str(x))

x= 0.3333333333333333


In [5]:
print("x= " + str(int(x))

SyntaxError: unexpected EOF while parsing (<ipython-input-5-c61f1ba0c8c8>, line 1)

In [6]:
int(x)

0

In [7]:
x

0.3333333333333333

In [8]:
print('weight = {} kg'.format(x))

weight = 0.3333333333333333 kg


In [9]:
print("weight = {} kg".format(x))

weight = 0.3333333333333333 kg


In [10]:
x=1/3
y=1/7
z=1/4
print('weight: {0} kg, {1} kg, {2} kg'.format(x,y,z))

weight: 0.3333333333333333 kg, 0.14285714285714285 kg, 0.25 kg


In [11]:
print('weight: {0:.2f} kg, {1:.2f} kg, {2:.2f} kg'.format(x,y,z))

weight: 0.33 kg, 0.14 kg, 0.25 kg


In [1]:
x=[1,1,2,3,5]
print(x)

[1, 1, 2, 3, 5]


In [2]:
x[0]

1

In [3]:
x[2]

2

In [4]:
print(type(x))

<class 'list'>


In [5]:
print(type(x[0]))

<class 'int'>


In [6]:
s=["SUN",1,"MON",2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


In [7]:
x[3]=100
print(x)

[1, 1, 2, 100, 5]


In [8]:
len(x)

5

In [9]:
a=[[1,2,3],[4,5,6]]
print(a)
print(type(a))
print(type(a[0]))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>
<class 'list'>


In [10]:
print(type(a[0][0]))

<class 'int'>


In [11]:
print(a[0][0])

1


連続した整数の配列の作成

In [12]:
y=range(5,10)
print(y[0],y[1],y[2],y[3],y[4])

5 6 7 8 9


In [13]:
len(y)

5

In [14]:
print(y)

range(5, 10)


In [15]:
print(type(y))

<class 'range'>


list型になっていない！

In [16]:
z=list(y)

In [17]:
print(z)

[5, 6, 7, 8, 9]


In [18]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

tupleはlistに似ているが要素の書き換えが不可

In [19]:
a=(1,2,3)
print(a)

(1, 2, 3)


In [20]:
a[0]

1

In [21]:
type(a)

tuple

In [22]:
a=(1)

In [23]:
type(a)

int

In [24]:
a=(1,)
type(a)

tuple

In [25]:
a=(0,1,2,3)
len(a)

4

In [26]:
a=tuple(range(0,10))
print(a)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


In [27]:
print(type(a))

<class 'tuple'>


In [1]:
x = 11
if x > 10:
    print("x is ")
    print("     larger than 10.")
else
    print("x is smaller than 11")

SyntaxError: invalid syntax (<ipython-input-1-87c287409aa7>, line 5)

In [2]:
x = 11
if x > 10:
    print("x is ")
    print("     larger than 10.")
else:
    print("x is smaller than 11")

x is 
     larger than 10.


In [3]:
#コメントです
x = 11
if x > 10:
    print("x is ")
    print("     larger than 10.")
else
    print("x is smaller than 11")

SyntaxError: invalid syntax (<ipython-input-3-3f6b00aec31b>, line 6)

In [4]:
x = 11
if x > 10:
    print("x is ")
    print("     larger than 10.")
else:
    print("x is smaller than 11")

x is 
     larger than 10.


In [5]:
x > 10

True

In [6]:
type(x > 10)

bool

In [7]:
x = 15
if 10 < x and x < 20:
    print("x is between 10 and 20.")

x is between 10 and 20.


In [8]:
for i in [1,2,3]:
    print(i)

1
2
3


In [9]:
num = [2,4,6,8,10]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


for in 変数 in list型 or tuple型 or range型

pythonではelegantな手法もある。

In [10]:
for i, n in enumerate(num):
    num[i] = n * 2
print(num)

[8, 16, 24, 32, 40]


indexとそれに対応する要素を取ってきてる感じ？

In [11]:
[1,2]+[3,4]

[1, 2, 3, 4]

ベクトル和ではなくlistが連結された。

NumPyを利用する

In [12]:
#numpyをnpとして使う。np.function名という形で用いる。
import numpy as np

In [13]:
#ベクトルの定義方法
x = np.array([1,2])
x

array([1, 2])

In [14]:
type(x)

numpy.ndarray

In [15]:
print(x)

[1 2]


In [16]:
x = np.array([1,2])
y = np.array([3,4])
print(x+y)

[4 6]


In [17]:
type(x+y)

numpy.ndarray

In [18]:
x+y

array([4, 6])

In [19]:
x = X+Y

NameError: name 'X' is not defined

In [20]:
x = x + y

In [21]:
x

array([4, 6])

In [22]:
x = np.array([1,2])

In [23]:
print(x[0])

1


In [24]:
x[0]

1

In [25]:
x[0]=100
print(x)

[100   2]


要素の値が1ずつ増えていくベクトル配列は、np.arrange(n)で作れる。

In [26]:
print(np.arrange(10))

AttributeError: module 'numpy' has no attribute 'arrange'

In [27]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [28]:
print(np.arange(5, 10))

[5 6 7 8 9]


ndarray型の注意点
b = aだとポインタが渡されるためbを変更するとaまで変更される。
b = a. copy()とするとbの変更はaに影響しない。

In [29]:
a = np.array([1,2,3])
b = a
print(a)
b[2] = 10
print(a)
print(b)

[1 2 3]
[ 1  2 10]
[ 1  2 10]


In [30]:
a = np.array([1,2,3])
b = a.copy()
print(a)
b[2] = 10
print(a)
print(b)

[1 2 3]
[1 2 3]
[ 1  2 10]


list型の場合はimport copyとしてからa = copy.deepcopy(b)

行列の扱い